spring.application.name=management
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/password_vault
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Migration (Recommended)
spring.flyway.enabled=true