spring.application.name=management
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/password_vault
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# (admin seed is now hardcoded in UserService: username=admin, password=admin123)
# Public URL of your app (used in invitation links)
app.base-url=http://localhost:8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mina.maleksabet05@gmail.com
spring.mail.password=uhgm opvh cbxg licb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

