ALTER TABLE audit_logs
DROP
CONSTRAINT fk_audit_user;

CREATE TABLE assignments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT,
    password_entry_id BIGINT,
    expires_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_assignments PRIMARY KEY (id)
);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_PASSWORD_ENTRY FOREIGN KEY (password_entry_id) REFERENCES password_entries (id);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE audit_logs CASCADE;